name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and deploy
        run: |
          npm install
          npm run build
          git config --global user.email "lundin.pontus@gmail.com"
          git config --global user.name "$GITHUB_ACTOR"
          git add dist && git commit -m "Initial dist subtree commit"
          REPOSITORY_PATH="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git push $REPOSITORY_PATH `git subtree split --prefix dist master`:gh-pages --force
        env:
          CI: true
